UnitTestとUITestを別々に実行するように変更

diff --git a/.github/workflows/ios.yml b/.github/workflows/ios.yml
--- a/.github/workflows/ios.yml
+++ b/.github/workflows/ios.yml
@@ -26,31 +26,21 @@ jobs:
       - name: List available schemes
         run: xcodebuild -list
         
-      - name: Set Default Scheme
-        run: |
-          scheme_list=$(xcodebuild -list -json | tr -d "\n")
-          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
-          echo $default | cat >default
-          echo Using default scheme: $default
-      
-      - name: Build
-        env:
-          scheme: ${{ 'default' }}
-          platform: ${{ 'iOS Simulator' }}
+      - name: Set Simulator Device
+        id: set_device
         run: |
           device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
-          if [ "$scheme" = "default" ]; then scheme=$(cat default); fi
-          if [ "$(ls -A | grep -i \\.xcworkspace\$)" ]; then
-            filetype_parameter="workspace"
-            file_to_build="$(ls -A | grep -i \\.xcworkspace\$)"
-          else
-            filetype_parameter="project"
-            file_to_build="$(ls -A | grep -i \\.xcodeproj\$)"
+          if [ -z "$device" ]; then
+            echo "Error: No available iOS Simulator found!"
+            exit 1
           fi
-          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
-          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device"
+          echo "DEVICE_NAME=$device" >> $GITHUB_ENV
+          echo "Using device: $device"
 
-      - name: Run Tests
+      - name: Run Unit Tests
         run: |
-          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone.*?[^\(]+' | head -1 | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
-          xcodebuild test -scheme "TodoAppTests" -destination "platform=iOS Simulator,name=$device"
+          xcodebuild test -scheme "TodoAppUnitTests" -destination "platform=iOS Simulator,name=${DEVICE_NAME}"
+
+      - name: Run UI Tests
+        run: |
+          xcodebuild test -scheme "TodoAppUITests" -destination "platform=iOS Simulator,name=${DEVICE_NAME}"
